language: go

services:
  - docker
addons:
   apt:
     sources:
       - git-core
     packages:
       - git

go:
  - "1.9.4"

before_install:
  - BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  - MODIFIED_DOCS=$(git diff --name-only $TRAVIS_COMMIT_RANGE | grep -E 'README.adoc|^docs/.*.adoc$' | wc -l)
  - COMMITS_WITH_FORCED_GEN=$(git log --format=%B  $TRAVIS_COMMIT_RANGE | grep -i "\[gen docs\]" | wc -l)
  - '[ $COMMITS_WITH_FORCED_GEN -gt 0 ] || [ $MODIFIED_DOCS -ge 1 ] && GENERATE_DOC=0 || GENERATE_DOC=1'
  - '[ "${BRANCH}" == "master" ] && [ "${TRAVIS_REPO_SLUG}" == "arquillian/ike-prow-plugins" ] || [ ! -z "${TRAVIS_PULL_REQUEST// }"  -a "${TRAVIS_PULL_REQUEST}" != "false" ] && GENERATE_DOC=0 || GENERATE_DOC=1'
  - 'if [ $GENERATE_DOC -eq 0 ]; then
      git config user.name "${GH_USER}";
      git config user.email "${GH_EMAIL}";
      git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*;
      git fetch origin gh-pages;
      git worktree add -b gh-pages gh-pages origin/gh-pages;
      GH_REF=$(git remote get-url origin | awk "{sub(/https:\/\//,\"https://${GH_TOKEN}@\")}; 1" | awk "{sub(/\.git/, \"\")} 1");
      docker pull rochdev/alpine-asciidoctor:mini;
    fi'

install:
  - GLIDE_VERSION="v0.13.1"
  - wget "https://github.com/Masterminds/glide/releases/download/$GLIDE_VERSION/glide-$GLIDE_VERSION-linux-amd64.tar.gz"
  - mkdir -p $HOME/bin
  - tar -vxz -C $HOME/bin --strip=1 -f glide-$GLIDE_VERSION-linux-amd64.tar.gz
  - export PATH="$HOME/bin:$PATH"
  - go get -u github.com/alecthomas/gometalinter && gometalinter --install
  - go get -u github.com/onsi/ginkgo/ginkgo
  - go get -u github.com/onsi/gomega

script:
  - make build
  - 'if [ $GENERATE_DOC -eq 0 ]; then
        ./.asciidoctor/generate.sh --keep;
     fi'

after_success:
  - 'if [ $GENERATE_DOC -eq 0 ]; then
      echo "Publishing documentation to gh-pages"
      cd gh-pages;
      git add .;
      git commit -m"docs: publishes new documentation";
      git push --quiet "${GH_REF}" gh-pages > /dev/null 2>&1;
      if [ ! -z "${TRAVIS_PULL_REQUEST// }" ] && [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then
        curl https://api.github.com/repos/${TRAVIS_REPO_SLUG}/issues/${TRAVIS_PULL_REQUEST}/comments -H "Authorization:token ${GH_TOKEN}" -X POST -d "{ \"body\": \"Greeting earthlings! Documentation is ready for preview at http://arquillian.org/ike-prow-plugins/pr/${TRAVIS_PULL_REQUEST}. Just be patient. It might take a few minutes for the changes to show up.\"}";
      fi;
    fi'

after_error:
  - 'if [ $GENERATE_DOC -eq 0 ]; then
      docker logs adoc-to-html;
    fi'

after_failure:
  - 'if [ $GENERATE_DOC -eq 0 ]; then
      docker logs adoc-to-html;
    fi'