# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

required = [
    "github.com/shurcooL/githubql",
    "github.com/satori/go.uuid",
    "k8s.io/test-infra/prow/cmd/hook"
    ]

[[override]]
  name = "github.com/alecthomas/gometalinter"
  revision = "46cc1ea3778b247666c2949669a3333c532fa9c6"

[[override]]
  name = "github.com/jteeuwen/go-bindata"
  revision = "6025e8de665b31fa74ab1a66f2cddd8c0abf887e"

[[override]]
  name = "golang.org/x/tools"
  revision = "77106db15f689a60e7d4e085d967ac557b918fb2"

# We need explicit UUID version due to conflicts with k8s code
[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

# Using this latest tag until a new version containing the
# commit cc3c003dafcc1261f914368c8bae8c7be1a6e2dc is released (so if anything newer than v15.0.0 is out)
[[constraint]]
  name = "github.com/google/go-github"
  revision = "437797734d06eec5394734a84cb5b59c82a66ee6"

[[constraint]]
  name = "k8s.io/test-infra"
  revision = "2f3ad698ffcff53f881d3292a1b3da894bf1d5f7"

# we need explicit shurcooL version due to conflicts with test-infra code
[[constraint]]
  name = "github.com/shurcooL/githubql"
  revision = "2f1beebeca3383d6367f59e5f091dd4fe1c856de"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/evalphobia/logrus_sentry"
  version = "0.4.5"

[[override]]
  name = "github.com/prometheus/client_golang"
  revision = "faf4ec335fe01ae5a6a0eaa34a5a9333bfbd1a30"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.3.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "gopkg.in/h2non/gock.v1"
  version = "1.0.8"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true