test_patterns:
  # Java
  - 'Test*.java'
  - '*Test.java'
  - '*Tests.java'
  - '*TestCase.java'
  - '*IT.java'

  # Go
  - '*_test.go'

  # JavaScript
  - '*test.js'
  - '*spec.js'

  # TypeScript
  - '*test.ts'
  - '*test.tsx'
  - '*spec.ts'
  - '*spec.tsx'

  # Python
  - 'test*.py'

  # Groovy
  - 'Test*.groovy'
  - '*Test.groovy'
  - '*Tests.groovy'
  - '*TestCase.groovy'
  - '*IT.groovy'

skip_validation_for:
  # Build tools files

  ## Go
  - 'regex{{glide.*}}'
  - 'regex{{Gopkg.*}}'
  
  ## Java
  - 'pom.xml'
  - 'mvnw'
  - 'mvnw.cmd'
  - 'mvnw.bat'
  - 'gradlew'
  - 'gradlew.bat'
  - 'build.gradle'
  
  ## JavaScript
  - 'regex{{package.*\.json$}}'
  - 'gulpfile.js'
  - 'Gruntfile.js'
  
  ## Ruby
  - 'Gemfile'
  - 'gemfile'
  
  ## Python
  - 'regex{{requirements.*}}'
  
  ## Docker
  - 'regex{{docker-compose.*\.y[a]?ml$}}'
  - 'Dockerfile*'
  - '.dockerignore'

  ## Others
  - 'Makefile'
  - 'Rakefile'
    
  # Build tools directories
  - 'gradle/'
  - 'vendor/'
  - '.mvn/'
  - '.make/'
  - 'node_modules/'

  # CI tools
  - 'Jenkinsfile'
  - 'regex{{\.travis\.y[a]?ml$}}'
  - 'regex{{\.gitlab-ci\.y[a]?ml$}}'
  - 'regex{{wercker\.y[a]?ml$}}'
  - 'regex{{circle\.y[a]?ml$}}'
  - 'regex{{codeship-services\.y[a]?ml$}}'
  - 'regex{{[\.]?codecov\.yml$}}'

  # UI assets
  - '*.jpg'
  - '*.jpeg'
  - '*.bmp'
  - '*.tif'
  - '*.tiff'
  - '*.png'
  - '*.ico'
  - '*.svg'
  - '*.gif'
  - '*.eps'
  - '*.css'
  - '*.scss'
  - '*.sass'
  - '*.less'
  - 'regex{{.*\.[xsd]?html$}}'
  - '*.ejs'
  - '*.raw'

  # Text assets
  - '*.md'
  - '*.txt'
  - '*.asciidoc'
  - '*.adoc'
  - 'LICENSE'
  - 'CODEOWNERS'

  # Configs
  - 'karma.conf.js'
  - 'regex{{protractor.*\.conf(ig)?\.js$}}'
  - 'regex{{\..+ignore}}'
  - '.editorconfig'
  - 'regex{{\..+rc}}'
  - 'regex{{tsconfig.*\.json$}}'
  - 'tslint.json' 
  - 'typedoc.json'
  - 'regex{{.codecov\.y[a]?ml$}}'
  - 'webpack.config.js'
  - 'regex{{\.sass-lint\.y[a]?ml$}}'
  - '*.gpg'
  - 'regex{{\.go.+_exclude}}'
  - 'pylint.rc'
  - 'pcp.repo'
  - '.github/'
  - '.gometalinter.json'
  - 'checkstyle.xml'
  
  # Shell
  - '*.sh'
  - '*.bat'

  # Our own configurations
  - 'regex{{test-keeper\.y[a]?ml$}}'
  - '.ike-prow/'
